#!/usr/bin/env python3
"""Emit the VM-side bootstrap prelude for Colab-CLI (headless) runs.

Colab Secrets (`google.colab.userdata`) only work when a browser frontend is
attached, so `userdata.get("HF_TOKEN")` raises `TimeoutException` in a session
created by `colab new` / `colab exec`. Rather than editing the notebooks, this
prelude runs once per session and monkeypatches `userdata.get` to serve the
token from a file already uploaded to the VM. Kernel state persists across
separate `colab exec` calls, so the patch is still in place when the notebook
runs afterwards.

The token is NEVER embedded in the emitted code: `colab exec` records every
executed code string verbatim in ~/.config/colab-cli/history/<session>.jsonl,
so an inlined secret would be written to a local plaintext log. Upload the
token as a file instead (`colab upload`, which logs only paths).

Usage:
    # one-time per session, after `colab upload ... /content/.hf_token`
    python tools/colab_cli_prelude.py --repo https://github.com/<you>/LagunaFineTune.git \
        | colab exec -s laguna

    # inspect what would run
    python tools/colab_cli_prelude.py --repo ...

Stdlib only. See COLAB_CLI.md for the full runbook.
"""

import argparse
import sys

TEMPLATE = '''\
# --- LagunaFineTune Colab-CLI prelude (generated by tools/colab_cli_prelude.py) ---
import os, subprocess, sys, pathlib

REPO_URL   = {repo!r}
BRANCH     = {branch!r}
CHECKOUT   = {checkout!r}
TOKEN_FILE = {token_file!r}
HF_HOME    = {hf_home!r}

# 1. Repo: clone once, then fast-forward on later runs so a re-run picks up pushes.
if not os.path.isdir(os.path.join(CHECKOUT, ".git")):
    subprocess.run(["git", "clone", "--depth", "50", "-b", BRANCH, REPO_URL, CHECKOUT],
                   check=True)
else:
    subprocess.run(["git", "-C", CHECKOUT, "fetch", "--depth", "50", "origin", BRANCH],
                   check=True)
    subprocess.run(["git", "-C", CHECKOUT, "reset", "--hard", "origin/" + BRANCH],
                   check=True)
if CHECKOUT not in sys.path:
    sys.path.insert(0, CHECKOUT)

# 2. Token: read from the uploaded file into the environment. src/hub_utils.py
#    reads os.environ["HF_TOKEN"], so this is what actually matters.
_tok_path = pathlib.Path(TOKEN_FILE)
if not _tok_path.is_file():
    raise SystemExit(
        "missing " + TOKEN_FILE + " -- upload it first:\\n"
        "  colab upload -s <session> ~/.config/laguna/hf_token " + TOKEN_FILE)
_tok = _tok_path.read_text().strip()
if not _tok:
    raise SystemExit(TOKEN_FILE + " is empty")
os.chmod(TOKEN_FILE, 0o600)
os.environ["HF_TOKEN"] = _tok
os.environ["HF_HOME"] = HF_HOME
os.environ.setdefault("HF_HUB_ENABLE_HF_TRANSFER", "0")

# 3. Shim google.colab.userdata so the UNMODIFIED notebooks keep working.
#    Without this, cell 1 of every notebook dies on userdata.get("HF_TOKEN").
try:
    from google.colab import userdata as _ud
except Exception as _e:  # not on a Colab VM
    print("warning: google.colab.userdata unavailable (" + repr(_e) + ")")
else:
    _orig_get = _ud.get

    def _patched_get(key):
        val = os.environ.get(key)
        if val:
            return val
        return _orig_get(key)

    _ud.get = _patched_get
    print("patched google.colab.userdata.get -> os.environ fallback")

# 4. Diagnostics (never print the token).
print("token bytes:", len(_tok), "| repo:", CHECKOUT, "| HF_HOME:", HF_HOME)
try:
    import torch
    if torch.cuda.is_available():
        _p = torch.cuda.get_device_properties(0)
        print("gpu:", _p.name, "|", round(_p.total_memory / 2**30, 1), "GiB",
              "| torch", torch.__version__)
    else:
        print("gpu: NONE VISIBLE -- wrong runtime? expected A100")
except Exception as _e:
    print("torch not importable yet:", repr(_e))
print("prelude OK")
'''


def build(repo, branch, checkout, token_file, hf_home):
    return TEMPLATE.format(repo=repo, branch=branch, checkout=checkout,
                           token_file=token_file, hf_home=hf_home)


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Emit the Colab-CLI session prelude on stdout.")
    ap.add_argument("--repo", required=True,
                    help="git URL of your LagunaFineTune fork")
    ap.add_argument("--branch", default="main")
    ap.add_argument("--checkout", default="/content/LagunaFineTune",
                    help="where to clone on the VM")
    ap.add_argument("--token-file", default="/content/.hf_token",
                    help="VM path of the uploaded HF token file")
    ap.add_argument("--hf-home", default="/content/hf_cache")
    args = ap.parse_args(argv)

    if "CHANGE_ME" in args.repo:
        ap.error("point --repo at your actual fork, not the CHANGE_ME placeholder")

    sys.stdout.write(build(args.repo, args.branch, args.checkout,
                           args.token_file, args.hf_home))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
